use gpui::*;
use gpui_component::StyledExt;

pub struct TimestampPage;

impl Render for TimestampPage {
    fn render(&mut self, _window: &mut Window, _cx: &mut Context<Self>) -> impl IntoElement {
        div()
            .size_full()
            .flex()
            .flex_col()
            .gap_4()
            .p_6()
            .child(div().text_lg().font_semibold().text_color(white()).child("时间戳转换"))
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap_5()
                    .child(
                        div()
                            .flex()
                            .items_center()
                            .justify_between()
                            .bg(rgb(0x2D2D2D))
                            .border_1()
                            .border_color(rgb(0x3C3C3C))
                            .rounded_lg()
                            .p_5()
                            .child(div().text_sm().text_color(white()).child("时间戳"))
                            .child(
                                div()
                                    .flex()
                                    .items_center()
                                    .gap_5()
                                    .child(
                                        div()
                                            .w(px(240.))
                                            .bg(rgb(0x1E1E1E))
                                            .border_1()
                                            .border_color(rgb(0x404040))
                                            .rounded_md()
                                            .p_3()
                                            .text_color(white())
                                            .child("输入时间戳..."),
                                    )
                                    .child(
                                        div()
                                            .w(px(96.))
                                            .bg(rgb(0x1E1E1E))
                                            .border_1()
                                            .border_color(rgb(0x404040))
                                            .rounded_md()
                                            .p_3()
                                            .text_sm()
                                            .text_color(white())
                                            .child("毫秒"),
                                    )
                                    .child(
                                        div()
                                            .px_4()
                                            .py_2()
                                            .bg(rgb(0x0078D4))
                                            .rounded_md()
                                            .text_sm()
                                            .text_color(white())
                                            .cursor_pointer()
                                            .hover(|style| style.bg(rgb(0x106EBE)))
                                            .child("当前时间"),
                                    ),
                            ),
                    )
                    .child(
                        div()
                            .flex()
                            .items_center()
                            .justify_between()
                            .bg(rgb(0x2D2D2D))
                            .border_1()
                            .border_color(rgb(0x3C3C3C))
                            .rounded_lg()
                            .p_5()
                            .child(div().text_sm().text_color(white()).child("时区选择"))
                            .child(
                                div()
                                    .w(px(480.))
                                    .bg(rgb(0x1E1E1E))
                                    .border_1()
                                    .border_color(rgb(0x404040))
                                    .rounded_md()
                                    .p_3()
                                    .text_sm()
                                    .text_color(white())
                                    .child("(UTC+08:00) 中国标准时间"),
                            ),
                    )
                    .child(
                        div()
                            .flex()
                            .items_center()
                            .justify_between()
                            .bg(rgb(0x2D2D2D))
                            .border_1()
                            .border_color(rgb(0x3C3C3C))
                            .rounded_lg()
                            .p_5()
                            .child(div().text_sm().text_color(white()).child("Common"))
                            .child(div().text_sm().text_color(rgb(0xA0A0A0)).child("2024-01-01 00:00:00")),
                    )
                    .child(
                        div()
                            .flex()
                            .items_center()
                            .justify_between()
                            .bg(rgb(0x2D2D2D))
                            .border_1()
                            .border_color(rgb(0x3C3C3C))
                            .rounded_lg()
                            .p_5()
                            .child(div().text_sm().text_color(white()).child("ISO 8601"))
                            .child(
                                div()
                                    .text_sm()
                                    .text_color(rgb(0xA0A0A0))
                                    .child("2024-01-01T00:00:00+08:00"),
                            ),
                    )
                    .child(
                        div()
                            .flex()
                            .items_center()
                            .justify_between()
                            .bg(rgb(0x2D2D2D))
                            .border_1()
                            .border_color(rgb(0x3C3C3C))
                            .rounded_lg()
                            .p_5()
                            .child(div().text_sm().text_color(white()).child("RFC 7231"))
                            .child(
                                div()
                                    .text_sm()
                                    .text_color(rgb(0xA0A0A0))
                                    .child("Mon, 01 Jan 2024 00:00:00 GMT"),
                            ),
                    ),
            )
    }
}
